[
  ./alias.nix
  ./documentation
  ./security/pki
  ./security/sandbox
  ./system
  ./system/checks.nix
  ./system/activation-scripts.nix
  ./system/applications.nix
  ./system/defaults-write.nix
  ./system/defaults/LaunchServices.nix
  ./system/defaults/NSGlobalDomain.nix
  ./system/defaults/GlobalPreferences.nix
  ./system/defaults/dock.nix
  ./system/defaults/finder.nix
  ./system/defaults/screencapture.nix
  ./system/defaults/smb.nix
  ./system/defaults/trackpad.nix
  ./system/etc.nix
  ./system/keyboard.nix
  ./system/launchd.nix
  ./system/shells.nix
  ./system/version.nix
  ./time
  ./networking
  ./nix
  ./nix/nix-darwin.nix
  ./nix/nix-info.nix
  ./nix/nixpkgs.nix
  ./environment
  ./fonts
  ./launchd
  ./services/activate-system
  ./services/autossh.nix
  ./services/buildkite-agent.nix
  ./services/chunkwm.nix
  ./services/emacs.nix
  ./services/hercules-ci-agent
  ./services/khd
  ./services/kwm
  ./services/mail/offlineimap.nix
  ./services/mopidy.nix
  ./services/nix-daemon.nix
  ./services/nix-gc
  ./services/ofborg
  ./services/postgresql
  ./services/privoxy
  ./services/redis
  ./services/skhd
  ./services/synapse-bt.nix
  ./services/synergy
  ./programs/bash
  ./programs/fish.nix
  ./programs/gnupg.nix
  ./programs/man.nix
  ./programs/info
  ./programs/nix-index
  ./programs/ssh
  ./programs/tmux.nix
  ./programs/vim.nix
  ./programs/zsh
  ./users
  ./users/nixbld
]
