[
  ./alias.nix
  ./documentation
  ./meta.nix
  ./misc/ids.nix
  ./misc/lib.nix
  ./security/pam.nix
  ./security/pki
  ./security/sandbox
  ./system
  ./system/checks.nix
  ./system/activation-scripts.nix
  ./system/applications.nix
  ./system/defaults-write.nix
  ./system/defaults/LaunchServices.nix
  ./system/defaults/NSGlobalDomain.nix
  ./system/defaults/GlobalPreferences.nix
  ./system/defaults/CustomPreferences.nix
  ./system/defaults/dock.nix
  ./system/defaults/finder.nix
  ./system/defaults/screencapture.nix
  ./system/defaults/alf.nix
  ./system/defaults/loginwindow.nix
  ./system/defaults/magicmouse.nix
  ./system/defaults/smb.nix
  ./system/defaults/SoftwareUpdate.nix
  ./system/defaults/spaces.nix
  ./system/defaults/trackpad.nix
  ./system/defaults/universalaccess.nix
  ./system/defaults/ActivityMonitor.nix
  ./system/etc.nix
  ./system/keyboard.nix
  ./system/launchd.nix
  ./system/patches.nix
  ./system/shells.nix
  ./system/version.nix
  ./time
  ./networking
  ./nix
  ./nix/nix-darwin.nix
  ./nix/nixpkgs.nix
  ./environment
  ./fonts
  ./launchd
  ./services/activate-system
  ./services/autossh.nix
  ./services/buildkite-agent.nix
  ./services/chunkwm.nix
  ./services/cachix-agent.nix
  ./services/dnsmasq.nix
  ./services/emacs.nix
  ./services/gitlab-runner.nix
  ./services/hercules-ci-agent
  ./services/karabiner-elements
  ./services/khd
  ./services/kwm
  ./services/lorri.nix
  ./services/mail/offlineimap.nix
  ./services/mopidy.nix
  ./services/monitoring/telegraf.nix
  ./services/netbird.nix
  ./services/nix-daemon.nix
  ./services/nix-gc
  ./services/ofborg
  ./services/postgresql
  ./services/privoxy
  ./services/redis
  ./services/skhd
  ./services/spacebar
  ./services/spotifyd.nix
  ./services/synapse-bt.nix
  ./services/synergy
  ./services/tailscale.nix
  ./services/wg-quick.nix
  ./services/yabai
  ./services/nextdns
  ./programs/bash
  ./programs/fish.nix
  ./programs/gnupg.nix
  ./programs/man.nix
  ./programs/info
  ./programs/nix-index
  ./programs/ssh
  ./programs/tmux.nix
  ./programs/vim.nix
  ./programs/zsh
  ./homebrew.nix
  ./users
]
